samples:
    id: "data"
    chroms: [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY]

modules:
    # rna 16s, 'frag_denovo',  'frag_denovo', 'align_ref'
    rna_16s: 'align_ref'

params:
    # sequence_type, pe or se, lower case
    sequence_type: 'pe'
    ref_fa_other: "ZymoBIOMICS.STD.refseq.v2.16s.dedup.fasta"
    n_frag: 100
    min_reads_bc: 50
    max_reads_bc: 1000

frag_de_novo:
    run_parallel: False
    reads_per_BC: 50
    margin: 5
    denovo_assembler: "SPAdes-3.14.0-Linux/bin/spades.py"
    spades_phred_offset: 55
    quast_dir: "quast/quast.py"
    quast_min_contig: 100
    quast_space_efficient: True
    minimap: "minimap2-2.16_x64-linux/minimap2"
    denovo_type: 'correct_rc'
    end_idx: 485000000
    start_idx: 1
    flank_end: 30
    adapter_seq: "CTCAGCAGAGGG"
    min_ctg_len: 400
    num_processes: 20 

threads:
    bwa: 100
    haplotyper: 100
    quast: 4

    